### ISSUE TITLE
Failure Due to Unquoted Paths with Spaces

### ISSUE THREAD

**Issue by LSXAxeller** [Afrino-co/EfCoreUI#2]
**Description:**
Executing a command like migrations add. update database, etc involving paths with spaces, such as:

```bash
C:\Program Files\dotnet\dotnet.exe ef migrations add --project X:\Personal Projects\XXXX\XXXX.Infrastructure\XXXX.Infrastructure.csproj --startup-project X:\Personal Projects\XXXX\XXXX.Presentation.API\XXXX.Presentation.API.csproj --context XXXX.Infrastructure.Data.Contexts.ApplicationDbContext --configuration Debug   Initial --output-dir Data\Migrations

  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet-ef does not exist.
Could not execute because the specified command or file was not found.
```

Results in a failure due to unquoted paths containing spaces. The command interpreter misinterprets spaces as delimiters, leading to path resolution errors.

**Solution:**
Enclose paths with spaces within double quotes ("") to ensure proper parsing by the command interpreter. For example:

```bash
"C:\Program Files\dotnet\dotnet.exe" ef migrations add --project "X:\Personal Projects\XXXX\XXXX.Infrastructure\XXXX.Infrastructure.csproj" --startup-project "X:\Personal Projects\XXXX\XXXX.Presentation.API\XXXX.Presentation.API.csproj" --context XXXX.Infrastructure.Data.Contexts.ApplicationDbContext --configuration Debug Initial --output-dir Data\Migrations
```

**Comment by masoodafar-web** [comment]
> **Description:** Executing a command like migrations add. update database, etc involving paths with spaces, such as:
> 
> ```shell
> C:\Program Files\dotnet\dotnet.exe ef migrations add --project X:\Personal Projects\XXXX\XXXX.Infrastructure\XXXX.Infrastructure.csproj --startup-project X:\Personal Projects\XXXX\XXXX.Presentation.API\XXXX.Presentation.API.csproj --context XXXX.Infrastructure.Data.Contexts.ApplicationDbContext --configuration Debug   Initial --output-dir Data\Migrations
> 
>   * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
> Possible reasons for this include:
>   * You misspelled a built-in dotnet command.
>   * You intended to execute a .NET program, but dotnet-ef does not exist.
> Could not execute because the specified command or file was not found.
> ```
> 
> Results in a failure due to unquoted paths containing spaces. The command interpreter misinterprets spaces as delimiters, leading to path resolution errors.
> 
> **Solution:** Enclose paths with spaces within double quotes ("") to ensure proper parsing by the command interpreter. For example:
> 
> ```shell
> "C:\Program Files\dotnet\dotnet.exe" ef migrations add --project "X:\Personal Projects\XXXX\XXXX.Infrastructure\XXXX.Infrastructure.csproj" --startup-project "X:\Personal Projects\XXXX\XXXX.Presentation.API\XXXX.Presentation.API.csproj" --context XXXX.Infrastructure.Data.Contexts.ApplicationDbContext --configuration Debug Initial --output-dir Data\Migrations
> ```

Hello, dear @LSXAxeller
Thank you for your feedback and effective communication.
The problem was solved in version 1.6 .
