### ISSUE TITLE
Configure startup project in code

### ISSUE THREAD

**Issue by Khaos66** [Afrino-co/EfCoreUI#3]
Hi! Thank's for the great extension <3

I found that the startup project is a random project every time I open the `add migration` dialog.

Would it be possible to define the startup project in code somehow, so that the correct startup project is selected each time the dialog is opened?

Maybe this could just be a setting in a `PropertyGroup` in a `Directory.Packages.Props` file?

```xml
<Project>
  <PropertyGroup>
    <EFCoreStartupProject>MyProject</EFCoreStartupProject>
  </PropertyGroup>
</Project>
```

**Comment by masoodafar-web** [comment]
Hello, dear @Khaos66 
Thank you for your cooperation and constructive feedback. I hope your problem has been solved with this new version.
I released a new version, in this version the config file is in the hidden **.vs** folder and the **EfCoreUiConfigFile.json** file is in the root folder of the project, check it out.
`[ProjectPath]/.vs/EfCoreUiConfigFile.json`
